sudo: required
services: docker
before_install:
  - docker build -t sain358/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sain358/react-test npm test -- --coverage
after_success:
  #  Build all images
  - docker build -t sain358/multi-client ./client
  - docker build -t sain358/multi-nginx ./nginx
  - docker build -t sain358/multi-server ./server
  - docker build -t sain358/multi-worker ./worker
  #  Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take images and push to docker hub
  - docker push sain358/multi-client
  - docker push sain358/multi-nginx
  - docker push sain358/multi-server
  - docker push sain358/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-multi"
  env: "DockerMulti-env"
  bucket: "elasticbeanstalk-eu-north-1-529917652448"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY